name: fetch-cluster-today
on:
  schedule:
    - cron: '00 6 * * *'
  workflow_dispatch:
jobs:
  fetch-cluster-data: 
    name: Fetch Today Cluster Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Set Timezone to Bangkok/Thailand
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Bangkok'
      - name : Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}
      - name: Setup Python Requirements
        run : pip install -r requirements.txt
      - name: Generate cluster data json from pdf
        working-directory: ./src
        run: |
          python process_pdf.py
      - name: Copy processed data to latest json
        working-directory: ./json
        run: cp cluster-data-* cluster-data.json
      - name: Upload json to wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: "./json"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
