name: fetch-cluster-today
on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  fetch-cluster-data:
    name: Fetch Today Cluster Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
      - name: Setup Python Requirements
        run : pip install -r requirements.txt
      - name: Generate cluster data json from pdf
        working-directory: ./src
        run: |
          python process_pdf.py
      - name: Upload json to wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: "./json"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
